### ISSUE TITLE
Ray.jl v0.0.1 release checklist

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/Ray.jl#149]
Required:
- [x] Decide if `ray_julia_jll` should be made into a submodule, and make it so (we decided to make this a submodule offline) #158 
- [x] Codecov badge has been added to README: https://github.com/beacon-biosignals/Ray.jl/pull/151
- [x] Most of the README has been transferred into docs: https://github.com/beacon-biosignals/Ray.jl/pull/153
- [x] Documentation is automatically built in CI: https://github.com/beacon-biosignals/Ray.jl/pull/153
- [x] Instructions exist for installing from pre-built binaries: https://github.com/beacon-biosignals/Ray.jl/pull/153
- [x] Instructions exist for contributing/developing Ray.jl: https://github.com/beacon-biosignals/Ray.jl/pull/153
- [x] A guide exists for building the pre-built binaries: https://github.com/beacon-biosignals/Ray.jl/pull/163
- [x] Format repo: https://github.com/beacon-biosignals/Ray.jl/pull/145

Optional:
- [ ] Ray.jl driver performs a runtime check when connecting to the Raylet to validate they are version compatible: https://github.com/beacon-biosignals/Ray.jl/issues/175
- [x] Use separate `Project.toml` for `build_jll.jl`: https://github.com/beacon-biosignals/Ray.jl/pull/150
- [x] Stop using `deps` directory. Combine with `gen` directory? Possibly rename to `cpp` or `build`: https://github.com/beacon-biosignals/Ray.jl/pull/159
- [ ] #84 
- [ ] Disable DEBUG logging for Ray in release

**Comment by omus** [comment]
We've released Ray.jl 0.0.1
